export const homeTypes = {
    GET_ASSETS_REQUEST: "GET_ASSETS_REQUEST",
    GET_ASSETS_SUCCESS: "GET_ASSETS_SUCCESS",
    GET_ASSETS_FAILURE: "GET_ASSETS_FAILURE",

    GET_PRICE_REQUEST: "GET_PRICE_REQUEST",
    GET_PRICE_SUCCESS: "GET_PRICE_SUCCESS",
    GET_PRICE_FAILURE: "GET_PRICE_FAILURE",
  };
  